#cloud-config
package_upgrade: true
packages:
  - openjdk-21-jdk
  - tomcat10
  - mysql-server
  - elinks
  - htop
write_files:
  - owner: developer:developer
    path: /home/developer/cloud_init_done.txt
    defer: true
    content: |
      Cloud init work is done!
